language: python

cache: pip

os:
  - linux

python:
  - '2.7'
  - '3.6'

install:
  - pip install -r requirements.txt
  - pip install pypandoc

script:
  - pycodestyle .
  - python setup.py test
  - python setup.py bdist_wheel

deploy:
  provider: pypi
  user: pylinksquare
  password:
    secure: YiEnTnpcHu9osvTPqW6//xxZvosQuEypJBCOrLuoYY6NoBPRgISZfxvoODUTYcYqttp+GKzQbSQ3rh9u4AjG4DuK8nt0lwMsi4RF9PBerGYM/db56Z9Azc7ZMttxozoAUAzDQaUGDEiyS4d5yPXq3OTlWZDWraG0btxVKYXtT7Mg8EuKtBgqVkFFdhRtC2zPuAttfsqTtvVxd42s/OUSd0LRCHrKEuGvKJ3XDNdPXp1pgOLuOJkP2YiBBB1RsUcIxr+xlPQLnjtxPeePhsNrsy5Bclnq8KqY0Gs9XgQ6WEF/4CR/g7WZ4g336TtORJJO1G8I1yZEaXEHQp1c65ZBgKzOkvTAa5/xWftrZRsqqE/H5B6d8FRV2MQnCbY/zzZu2mnZjkbvs0e6C44Sv+yoQIedVz0sawucXCjBjT0eyK8hgbCEFW0nzpiqm72l/fBhiUju0akskCpAsDVgVMx2dAH1syHdh17Mgc90fnNm6DSfNA+u/Jf6Fep5o/f6m1qIWuoVrgWoQ1550YFo08JFOl8ye0qx9Eg8ETe/bkUpq5h4Mgwy5g9wVRHCR6WQbQB4WsJH5iB5QPdiDJhauJyGWu3x/zIHtyChOHdPHuq3E65qcrYJHITQDbR6WZNm8AeWzW5e0CHUhDflKhAwNZzAAewtOllnDS2m/NoP3G555wg=
  on:
    branch: master
    tags: true
  distributions: "sdist bdist_wheel"

addons:
  apt:
    packages:
      - pandoc
