name: Publish Python distributions to TestPyPi and PyPi

on:
  release:
    types: [ published ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/project/pylink-square/
    permissions:
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
      - name: Set up Python 3.11
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97
        with:
          python-version: '3.11'
      - name: Install Dependencies
        run: |
          sudo apt-get install pandoc
          python -m pip install --upgrade pip
          pip install pypandoc
          pip install -e ".[dev,test]"
      - name: Test Package
        run: |
          python -m unittest
      - name: Build Package
        run: |
          python setup.py bdist_wheel sdist
      - name: Publish Package
        uses: pypa/gh-action-pypi-publish@dc37677b2e1c63e2034f94d8a5b11f265b73ba33
        with:
          user: __token__
          packages_dir: ./dist/
